import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JFileChooser;
 
/**
*
* @author yanda
*/
public class notes extends javax.swing.JFrame {
private boolean tersimpan = false;
private String bug_file=" ";
private String judul_default ="Noname";
private String judul =judul_default;
 
/**
* Creates new form notes
*/
public notes() {
super("Noname");
initComponents();
}
 
/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtex = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jnew = new javax.swing.JMenuItem();
        jopen = new javax.swing.JMenuItem();
        jsave = new javax.swing.JMenuItem();
        jsaveas = new javax.swing.JMenuItem();
        jexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtex.setColumns(20);
        jtex.setRows(5);
        jScrollPane1.setViewportView(jtex);

        jMenu1.setText("Opsi Menu");

        jnew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jnew.setText("New");
        jnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewActionPerformed(evt);
            }
        });
        jMenu1.add(jnew);
        jnew.getAccessibleContext().setAccessibleDescription("");

        jopen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jopen.setText("Open");
        jopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jopenActionPerformed(evt);
            }
        });
        jMenu1.add(jopen);

        jsave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jsave.setText("Save");
        jsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaveActionPerformed(evt);
            }
        });
        jMenu1.add(jsave);

        jsaveas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jsaveas.setText("Save As");
        jsaveas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaveasActionPerformed(evt);
            }
        });
        jMenu1.add(jsaveas);

        jexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jexit.setText("Exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        jMenu1.add(jexit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jopenActionPerformed
        // TODO add your handling code here:
        JFileChooser open = new JFileChooser();
        int option = open.showOpenDialog(open);
        if (option == JFileChooser.APPROVE_OPTION){
            jtex.setText("");
            try {
                Scanner scan = new Scanner(new FileReader(open.getSelectedFile().getPath()));
                while (scan.hasNext())
                    jtex.append(scan.nextLine()+" ");
                judul = open.getSelectedFile().getName()+" ";
                this.setTitle(judul);
                tersimpan = true;
                bug_file = open.getSelectedFile().getPath();
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jopenActionPerformed

    private void jnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewActionPerformed
        // TODO add your handling code here:
        judul=judul_default;
        this.setTitle(judul);
        tersimpan = false;
        jtex.setText("");
    }//GEN-LAST:event_jnewActionPerformed

    private void jsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaveActionPerformed
        // TODO add your handling code here:
        if (tersimpan=true){
            try(BufferedWriter out = new BufferedWriter(new FileWriter(bug_file))){
                out.write(jtex.getText());
                judul=judul;
                this.setTitle(judul);
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
        }
        //menyimpan file baru
        else {
            JFileChooser save = new JFileChooser();
            int option = save.showOpenDialog(save);
            if (option== JFileChooser.APPROVE_OPTION){
                try{
                    try(BufferedWriter out = new BufferedWriter(new FileWriter(save.getSelectedFile().getPath()))){
                        out.write(jtex.getText());
                    }
                    judul=save.getSelectedFile().getName()+""+judul;
                    this.setTitle(judul);
                    tersimpan = true;
                    bug_file = save.getSelectedFile().getPath();
                }catch(Exception ex){
                    System.out.println(ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jsaveActionPerformed

    private void jsaveasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaveasActionPerformed
        // TODO add your handling code here:
        JFileChooser save = new JFileChooser();
        int option = save.showOpenDialog(save);
        if (option== JFileChooser.APPROVE_OPTION){
            try{
                try(BufferedWriter out = new BufferedWriter(new FileWriter(save.getSelectedFile().getPath()))){
                    out.write(jtex.getText());
                }
                judul=save.getSelectedFile().getName()+""+judul;
                this.setTitle(judul);
                tersimpan = true;
                bug_file = save.getSelectedFile().getPath();
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jsaveasActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jexitActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>
/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new notes().setVisible(true);
}
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jexit;
    private javax.swing.JMenuItem jnew;
    private javax.swing.JMenuItem jopen;
    private javax.swing.JMenuItem jsave;
    private javax.swing.JMenuItem jsaveas;
    private javax.swing.JTextArea jtex;
    // End of variables declaration//GEN-END:variables
}